//--------------------------------------------------------
//DJYOS components configuration file.
//This file is generated by "com.djyos.utilities" plugin
//Sun Sep 29 16:48:11 CST 2013
//--------------------------------------------------------

#ifndef __CONFIG_PRJ_H_
#define __CONFIG_PRJ_H_

#ifdef __cplusplus
extern "C" {
#endif

/*____与硬件相关的配置____*/
#define Mhz 1000000
#define CN_CFG_MCLK (400*Mhz)  //主频
//#define CN_CFG_FCLK CN_CFG_MCLK  //cm3自由运行外设时钟
//#define CN_CFG_AHBCLK CN_CFG_MCLK  //总线时钟
//#define CN_CFG_PCLK2 CN_CFG_MCLK  //高速外设时钟
#define CN_CFG_PCLK1 (CN_CFG_MCLK/2)  //低速外设时钟
#define CN_CFG_EXTCLK 25000000  //外部时钟=8M
//#define cfg_core_ccb_clk (400*Mhz)
//#define cfg_core_implete_clk (cfg_core_ccb_clk/8)  //tbclk
//#define cfg_rtc_clk 800*Mhz


/*____以下定义tick参数____*/
#define CN_CFG_TICK_US 1000  //操作系统内核时钟脉冲长度，以us为单位。
#define CN_CFG_TICK_HZ 1000  //内核时钟频率，单位为hz。
#define CN_CFG_FINE_US 0x00000a3d  //40nS,精密时钟脉冲长度，以uS为单位，32位定点数整数、小数各占16位，这也限制了ticks最长不超过65535uS
#define CN_CFG_FINE_HZ (25*Mhz)  //内核精密时钟频率，是cn_fine_ns的倒数。

/*____时间相关设置____*/
#define CN_CFG_TIME_MODULE 1  //是否包含时间模块
#define CN_CFG_TIME_ZONE (+8)  //本地时区
#define CN_CFG_TIME_SRC_TICK 0  //内核嘀嗒脉冲做走时基准
#define CN_CFG_TIME_SRC_RTC 1  //硬件rtc做走时基准
#define CN_CFG_TIME_SRC CN_CFG_TIME_SRC_TICK  //选择走时基准

/*____cpu运行模式定义____*/
#define CN_MODE_TINY 0  //tiny模式
#define CN_MODE_SI 1  //单映像模式
#define CN_MODE_DLSP 2  //动态加载单进程模式
#define CN_MODE_MP 3  //多进程模式，只有mmu=true才可选择此模式
#define CN_CFG_RUN_MODE CN_MODE_SI

/*____字符集，支持gui kernel，本组配置才有意义____*/
#define CN_CFG_CHARSET_GB2312 0  //gb2312编码
#define CN_CFG_CHARSET_ASCII 0  //gb2312已经包含了ascii编码，无须再支持
#define CN_CFG_CHARSET_UTF8 0  //unicode最流行的一种编码方式
#define CN_CFG_CHARSET_DEFAULT "gb2312"  //此名字须与C文件中定义的字符集名字相同

/*____字体，支持gui kernel，本组配置才有意义____*/
#define CN_CFG_GB2312_8x16_1616 0  //包含8*16点阵的ascii字符和16*16点阵的宋体汉字
#define CN_CFG_ASCII_8x8 0  //包含8*8点阵的ascii字符
#define CN_CFG_ASCII_6x12 0  //包含6*12点阵的ascii字符
#define CN_CFG_ASCII_8x16 0  //包含8*16点阵的ascii字符gb2312_816_1616中已经包含，无须单独定义
#define CN_CFG_FONT_DEFAULT "gb2312_8_16_1616"  //此名字须与C文件中使用的字体资源名字相同,

/*____gui kernel配置____*/
#define CN_CFG_GUI_KERNEL 0  //gui kernel模块
#define CN_CFG_DOWN_CHUNNEL_DEEP 1024  //控制命令缓存深度，字节数
#define CN_CFG_GK_UP_CHUNNEL_DEEP 256  //gui kernel消息缓冲区长度，字节数
#define CN_CFG_GUI_PATTERN_MODE 0  //模式位图尺寸，0=固定8*8位图，1=任意bitmap（V1.0.0不支持）

/*____数量控制____*/
#define CN_CFG_DEVICE_LIMIT 10  //定义设备数量。
#define CN_CFG_LOCKS_LIMIT 20  //定义程序中可用的自由锁的数量。自由锁指用户调用semp_create和mutex_create创建的锁，不包括内核用到的锁。
#define CN_CFG_EVENTS_LIMIT 10  //事件数量
#define CN_CFG_EVTTS_LIMIT 10  //总事件类型数
#define CN_CFG_PARAS_LIMIT 20  //事件参数数量，
#define CN_CFG_WDTS_LIMIT 5  //允许养狗数量
#define CN_CFG_PIPES_LIMIT 0  //管道数量

/*____与内存管理相关的常量____*/
#define CN_CFG_VIRTUAL_MEMORY 0  //m3硬件不支持虚拟内存，如果在硬件支持虚拟内存的机器上，软件不打算支持，也设为0
#define CN_CFG_PHY_MEMORY 0  //物理内存总量，支持虚拟内存才有意义。
#define CN_CFG_PAGE_SIZE 32  //基页尺寸为4Kbytes
#define CN_CFG_PAGE_SIZE_SUFFIX_ZERO 5  //页尺寸后缀0的个数
#define CN_CFG_MEM_RECYCLE true  //支持内存回收----配置工具
#define CN_CFG_MEM_POOLS 5  //允许建立5个内存池
#define CN_CFG_SYSSVC_STACK 512  //系统服务事件栈容量
#define CN_CFG_DYNAMIC_MEM 0  //是否支持高级内存分配，即使不支持，也允许使用malloc-free分配内存，但必须严格成对调用，否则会内存泄漏
#define CN_CFG_STACK_FILL 'd'  //栈填充值，设为0则不填充
#define CN_CFG_CACHE_USED 0  //cache
#define CN_CFG_MAIN_STACK 1536  //main函数所需栈容量

/*____文件系统相关配置____*/
#define CN_CFG_DJYFS 1  //是否包含文件系统
#define CN_CFG_DJYFS_EASY_FLASH 1  //定义easy nor flash 文件系统
#define CN_CFG_DJYFS_FLASH 0  //是否包含flash文件系统的驱动
#define CN_CFG_FAT_FILESYS 0  //是否包含flash文件系统的驱动
#define CN_CFG_DJYFS_RAM 0  //是否包含ram文件系统
#define CN_CFG_OPENED_FSNODE_LIMIT 5  //可同时打开的文件数量，注意多级路径的每一级都算一个文件，但相同的路径不重复算
#define CN_CFG_EASYNOR_START_SECTOR       40 //定义简易文件系统起始块
#define CN_CFG_EASYNOR_LENGTH_SECTOR      192  //定义文件系统占用sector个数

/*____组件配置____*/
#define CN_CFG_PAN_DRIVER 1  //是否包含泛设备驱动模块
#define CN_CFG_DEBUG_INFO 1  //调试信息收集与输出模块
#ifdef Monitor_version
	#define CN_CFG_SHELL 1  //是否包含shell模块
#endif
#ifdef Release_version
	#define CN_CFG_SHELL 1  //是否包含shell模块
#endif
#define CN_CFG_XMODEM 0 //是否包含xmodem
#define CN_CFG_PIPE 0  //是否包含管道通信模块
#define CN_CFG_WDT 0  //是否包含看门狗驱动
#define CN_CFG_NUDE_TERMINAL 0  //nude terminal是一个在启动时提供最基本的人机对话功能的模块
#define CN_CFG_DJYIP 0  //djyip 模块

/*____标准输入模块配置____*/
#define CN_CFG_KEYBOARD 0  //是否包含键盘驱动
#define CN_CFG_SINGLE_TOUCH 0  //是否支持单点触摸屏
#define CN_CFG_MUTI_TOUCH 0  //是否支持多点触摸屏
#define CN_CFG_MUTI_KEYBOARD 0  //0=不支持多键盘，即使系统拥有多键盘，所有键盘也不加区分地使用
#define CN_CFG_MUTI_MOUSE_2D 0  //0=不支持多鼠标，即使系统拥有多个鼠标，所有鼠标也共享同一个鼠标指针。
#define CN_CFG_MUTI_MOUSE_3D 0  //0=不支持多3d鼠标，即使系统拥有多个3d鼠标，所有鼠标也共享同一个鼠标指针。
#define CN_CFG_STDIN_DEVICE "uart1"  //标准输入设备
#define CN_CFG_STDIN_DEVICE_LIMIT 3  //可支持的输入设备数量

/*____外设配置____*/
#define CN_CFG_UART1_USED 1
#define CN_CFG_UART2_USED 0
#define CN_CFG_UART3_USED 0
#define CN_CFG_UART4_USED 0
#define CN_CFG_UART5_USED 0

/*____工作路径设置____*/
#define CN_CFG_WORK_PATH "easy nor flash:\\"  //工作路径设置用户不设置的话，set_work_path就是空字符

/*____板级外设设置____*/
//RTC_DS1390
#define CFG_RTC_SPI_BUS			SPI1        //RTC使用的SPIx
#define CFG_RTC_SPI_CS			2			//SS2
#define CFG_RTC_SPI_SPEED		600000      //RTC传递的SPI速度 600kHz
//SPI_FLASH_AT45DB321D
#define AT45_Page_Size			512
#define CFG_FLASH_SPI_BUS		SPI1        //FLASH使用的SPIx
#define CFG_FLASH_SPI_CS		0			//SS0
#define CFG_FLASH_SPI_SPEED		1000000     //FLASH传递的SPI速度 600kHz


#ifdef __cplusplus
}
#endif
#endif

