//--------------------------------------------------------
//DJYOS components configuration file.
//This file is generated by "com.djyos.utilities" plugin
//Tue Dec 25 11:46:35 CST 2012
//--------------------------------------------------------

#ifndef __CONFIG_PRJ_H_
#define __CONFIG_PRJ_H_


#ifdef __cplusplus
extern "C" {
#endif


#include "stdint.h"

#ifdef __cplusplus
extern "C" {
#endif

extern const u32 gc_u32CfgTimeZone;     //本地时区为东8区(北京)

extern const char *gc_pCfgDefaultCharsetName;  //默认字符集
extern const char *gc_pCfgDefaultFontName;  //默认字体

extern const u32 gc_u32CfgGuiCmdDeep;   //gkernel命令缓冲区深度(字节数,非命令条数)
extern const u32 gc_u32CfgGuiStsDeep;    //gkernel状态缓冲区深度(字节数,非命令条数)

extern const u32 gc_u32CfgDeviceLimit;     //定义设备数量。
extern const u32 gc_u32CfgLockLimit;       //定义锁数量。用户调用semp_create和mutex_create创建的锁，不包括内核用到的锁。
extern const u32 gc_u32CfgEventLimit;      //事件数量
extern const u32 gc_u32CfgEvttLimit;       //总事件类型数
extern const u32 gc_u32CfgWdtLimit;        //允许养狗数量
extern const u32 gc_u32CfgPipeLimit;       //管道数量
extern const u32 gc_u32CfgMemPoolLimit;    //允许建立5个内存池
extern const u32 gc_u32CfgStdinDeviceLimit;
extern const u32 gc_u32CfgMainStackLen;

extern const u32 gc_u32CfgOpenedfileLimit;
extern const u32 gc_u32CfgTimerLimit;

extern const char *gc_pCfgStdinName;        //标准输入设备
extern const char *gc_pCfgStdoutName;       //标准输出设备
extern const char *gc_pCfgStderrName;       //标准错误输出设备
extern const char *gc_pCfgWorkPath;         //工作路径设置
#ifdef __cplusplus
}
#endif
#endif

