//--------------------------------------------------------
//DJYOS components configuration file.
//This file is generated by "com.djyos.utilities" plugin
//Sat Jun 09 10:13:08 CST 2012
//--------------------------------------------------------

#ifndef __CONFIG_PRJ_H_
#define __CONFIG_PRJ_H_

#ifdef __cplusplus
extern "C" {
#endif


/*____与硬件相关的配置____*/
#define CN_CFG_TICK_US 1000  //操作系统内核时钟脉冲长度，以微秒为单位。
#define CN_CFG_TICK_HZ 1000  //内核时钟频率，单位为hz。

/*____时间相关设置____*/
#define CN_CFG_TIME_MODULE 0  //是否包含时间模块
#define CN_CFG_TIME_ZONE (+8)  //本地时区
#define CN_CFG_TIME_SRC_TICK 0  //内核嘀嗒脉冲做走时基准
#define CN_CFG_TIME_SRC_RTC 1  //硬件rtc做走时基准
#define CN_CFG_TIME_SRC CN_CFG_TIME_SRC_TICK  //选择走时基准

/*____cpu运行模式定义____*/
#define CN_MODE_TINY 0  //tiny模式
#define CN_MODE_SI 1  //单映像模式
#define CN_MODE_DLSP 2  //动态加载单进程模式
#define CN_MODE_MP 3  //多进程模式，只有mmu=true才可选择此模式
#define CN_CFG_RUN_MODE CN_MODE_TINY

/*____gui kernel配置____*/
#define CN_CFG_GUI_KERNEL 0  //是否包含gui kernel模块
#define CN_CFG_DOWN_CHUNNEL_DEEP 1024  //控制命令缓存深度，字节数
#define CN_CFG_GK_UP_CHUNNEL_DEEP 256  //gui kernel消息缓冲区长度，字节数

/*____字符集，支持gui kernel，本组配置才有意义____*/
#define CN_CFG_CHARSET_GB2312 0  //gb2312编码
#define CN_CFG_CHARSET_ASCII 0  //gb2312已经包含了ascii编码，无须再支持
#define CN_CFG_CHARSET_UTF8 0  //unicode最流行的一种编码方式
#define CN_CFG_CHARSET_DEFAULT "gb2312"  //此名字须与C文件中定义的字符集名字相同

/*____字体，支持gui kernel，本组配置才有意义____*/
#define CN_CFG_GB2312_8x16_1616 0  //包含8*16点阵的ascii字符和16*16点阵的宋体汉字
#define CN_CFG_ASCII_8x8 0  //包含8*8点阵的ascii字符
#define CN_CFG_ASCII_8x16 0  //包含8*16点阵的ascii字符gb2312_816_1616中已经包含，无须单独定义
#define CN_CFG_FONT_DEFAULT "gb2312_8_16_1616"  //此名字须与C文件中使用的字体资源名字相同,

/*____数量控制____*/
#define CN_CFG_DEVICE_LIMIT 0  //定义设备数量。
#define CN_CFG_LOCKS_LIMIT 5  //定义程序中可用的自由锁的数量。自由锁指用户调用semp_create和mutex_create创建的锁，不包括内核用到的锁。
#define CN_CFG_EVENTS_LIMIT 5  //事件数量
#define CN_CFG_EVTTS_LIMIT 5  //总事件类型数
#define CN_CFG_PARAS_LIMIT (CN_CFG_EVENTS_LIMIT+CN_CFG_EVTTS_LIMIT)  //事件参数数量，
#define CN_CFG_WDTS_LIMIT 0  //允许养狗数量
#define CN_CFG_PIPES_LIMIT 0  //管道数量

/*____与内存管理相关的常量____*/
#define CN_CFG_VIRTUAL_MEMORY 0  //m3硬件不支持虚拟内存，如果在硬件支持虚拟内存的机器上，软件不打算支持，也设为0
#define CN_CFG_PHY_MEMORY 0  //物理内存总量，支持虚拟内存才有意义。
#define CN_CFG_PAGE_SIZE 0x20  //基页尺寸为32bytes
#define CN_CFG_PAGE_SIZE_SUFFIX_ZERO 5  //页尺寸后缀0的个数
#define CN_CFG_MEM_POOLS 5  //允许建立5个内存池
#define CN_CFG_SYSSVC_STACK 256  //系统服务事件栈容量
#define CN_CFG_DYNAMIC_MEM 0  //是否支持高级内存分配，即使不支持，也允许使用malloc-free分配内存，但必须严格成对调用，否则会内存泄漏
#define CN_CFG_STACK_FILL 'd'  //栈填充值，设为0则不填充
#define CN_MAIN_STACK 1024  //main函数所需栈容量

/*____文件系统相关配置____*/
#define CN_CFG_DJYFS 0  //是否包含文件系统
#define CN_CFG_DJYFS_FLASH 0  //是否包含flash文件系统的驱动
#define CN_CFG_FAT_FILESYS 0  //是否包含flash文件系统的驱动
#define CN_CFG_DJYFS_RAM 0  //是否包含ram文件系统
#define CN_CFG_OPENED_FSNODE_LIMIT 0  //可同时打开的文件数量，注意多级路径的每一级都算一个文件，但相同的路径不重复算

/*____组件配置____*/
#define CN_CFG_PAN_DRIVER 0  //是否包含泛设备驱动模块
#define CN_CFG_DEBUG_INFO 0  //调试信息收集与输出模块
#define CN_CFG_SHELL 0  //是否包含shell模块
#define CN_CFG_PIPE 0  //是否包含管道通信模块
#define CN_CFG_WDT 0  //是否包含看门狗驱动
#define CN_CFG_NUDE_TERMINAL 0  //nude terminal是一个在启动时提供最基本的人机对话功能的模块
#define CN_CFG_DJYIP 0  //djyip 模块

/*____标准输入模块配置____*/
#define CN_CFG_KEYBOARD 0  //是否包含键盘驱动
#define CN_CFG_SINGLE_TOUCH 0  //是否支持单点触摸屏
#define CN_CFG_MUTI_TOUCH 0  //是否支持多点触摸屏
#define CN_CFG_MUTI_KEYBOARD 0  //0=不支持多键盘，即使系统拥有多键盘，所有键盘也不加区分地使用
#define CN_CFG_MUTI_MOUSE_2D 0  //0=不支持多鼠标，即使系统拥有多个鼠标，所有鼠标也共享同一个鼠标指针。
#define CN_CFG_MUTI_MOUSE_3D 0  //0=不支持多3d鼠标，即使系统拥有多个3d鼠标，所有鼠标也共享同一个鼠标指针。
#define CN_CFG_STDIN_DEVICE ""  //标准输入设备
#define CN_CFG_STDIN_DEVICE_LIMIT 0  //可支持的输入设备数量

/*____外设配置____*/
#define CN_CFG_UART0_USED 0
#define CN_CFG_UART1_USED 0
#define CN_CFG_UART2_USED 0
#define CN_CFG_UART3_USED 0

/*____工作路径设置____*/
#define CN_CFG_WORK_PATH "sys:\\"  //工作路径设置用户不设置的话，set_work_path就是空字符

#ifdef __cplusplus
}
#endif
#endif

